dist: trusty
sudo: required

language: python

python:
  - "2.6"
  - "2.7"

before_install: ./scripts/travis-install-build-deps.sh

install: true

script:
  - make check-style
  - python setup.py sdist
  - ./scripts/pycam --help
