dist: xenial

before_install:
        - ./scripts/travis-install-build-deps.sh
        - sudo apt-get install -y python-flake8 python-pytest

install: true

script:
  - export BRANCH=$(if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then echo ${TRAVIS_BRANCH}; else echo ${TRAVIS_BRANCH}-${TRAVIS_PULL_REQUEST_BRANCH}-pr${TRAVIS_PULL_REQUEST}; fi)
  - git branch -D ${BRANCH} || true
  - git checkout -b ${BRANCH} ${TRAVIS_COMMIT}
  - make test
  - python setup.py sdist
  - dpkg-buildpackage -us -uc
  - ./scripts/pycam --help
