dist: trusty
sudo: required

language: python

python:
  - "2.6"
  - "2.7"

before_install: ./scripts/travis-install-build-deps.sh

script:
  - make check-style || true
  - python setup.py sdist
  - ./scripts/pycam --help
